sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

script:
  - ./gradlew build
  - cd subprojects/backend
  - ../../gradlew createDockerfile
  - cd build
  - docker build -t kaitoedter/chatty .
  - docker login --email="$DOCKER_EMAIL" --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push kaitoedter/chatty
  - docker login --email=_ --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
  - docker tag kaitoedter/chatty registry.heroku.com/chatty42/web
  - docker push registry.heroku.com/chatty42/web
  - cd ../../..

#deploy:
#  provider: heroku
#  api_key:
#    secure: T+25rIkOT1erceI6nJ7Y1hYASsnTuMDqEzLcJHNbmuaDXiaiyVs9RUnmWLCpEHz4bzvwlcojYWis2sFD0/Iu7ajZOwW9PtCH4uCE0ZwkHS/NlxPYbKDEpGW+BSDSildxdFU/9pGQgKy+wt5w6bslo8j17m5CK410htt6sAiS+tE=
#  app: chatty42
#  on:
#    repo: toedter/chatty
